/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(home)': RouteRecordInfo<
      '/(home)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/oauth/callback': RouteRecordInfo<
      '/oauth/callback',
      '/oauth/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/p/[projectId]': RouteRecordInfo<
      '/p/[projectId]',
      '/p/:projectId',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    '/projects': RouteRecordInfo<
      '/projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signin': RouteRecordInfo<
      '/signin',
      '/signin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/signup': RouteRecordInfo<
      '/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(home).vue': {
      routes:
        | '/(home)'
      views:
        | never
    }
    'src/pages/oauth/callback.vue': {
      routes:
        | '/oauth/callback'
      views:
        | never
    }
    'src/pages/p/[projectId].vue': {
      routes:
        | '/p/[projectId]'
      views:
        | never
    }
    'src/pages/projects.vue': {
      routes:
        | '/projects'
      views:
        | never
    }
    'src/pages/signin.vue': {
      routes:
        | '/signin'
      views:
        | never
    }
    'src/pages/signup.vue': {
      routes:
        | '/signup'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
